provider: {linux_ppc64le: default}
travis:
  secure:
    BINSTAR_TOKEN: qfJabT5+3T7GVE8GGSfTOQDubQ+sUWLefzM13OnlF/P6PPoDN/9Ni8zuXMd3HSQpTb5iKINUGV97WZXjGFD3ILnrRBj/MF4FHf5WjiMckTcIK0XMZQlIbHGvd1d7NIRg14vjg6HgipfGAQs2iJf6KQXy9BsYIGKXZrYtH8eeHKAy1rbJI27347ZfJ0TcARfZwotCN35qGGZKOmXXCGTV04agJ8k9ARaCHTXGHV3X91RlS3jWxw3OQeokerYbDuBvFqKIeQuYnJ7anxnPoBshbDC4ORhnw/Rh5qNpAkf1XwTPsRxrOWKxywP2JHAdPFgnkVj7hLaeOedupZqlgdBk0y0/bNNsGOxR9Ke9vOmEyPoQi0YuXp0hva0S0C3vwvkemjXURK1dM7otAE2Y64HqQGcMB+x8xJXTEqoqkfiPgI+BV4cevWmGiUnDoIqLazlQwqL8bCvyYZYqPe1qFOVRLL7p3htjyQ3G0eoHThWtVio+/5sbjavzTnWIMKaCLb3QvPVcGTXfhnnKuPb2u1fOCYGODEpWSNW3wR+xfFj6tNDeBeEW/jxBjIEWkuSz+Yd0Fcr1144Vtm6Iu4HEbQ21tvMmXSIa0P91DugrznwMMs7mzGEw77bWg07V3wsZIvFcEbrIcUBCMuzOJy5dQ9mozoCFvKxxOzT5q04cVWI4h1A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
